In [3]:
!pip install numpy

In [4]:
import numpy as np

In [6]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [7]:
a=np.array([[1,2,3],[4,5,6]])
print(a)


[[1 2 3]
 [4 5 6]]


In [9]:
#ndarray.shape
a=np.array([[1,2,3],[4,5,6]] )
print(a.shape)

(2, 3)


In [11]:
a=np.array([[1,2,3],[4,5,6]] )
a.shape=(3,2)

In [12]:
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [13]:
#ndarray.ndim
a=np.arange(24)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [14]:
type(a)

numpy.ndarray

In [15]:
a[0]

0

In [16]:
a[3]

3

In [17]:
b=a.reshape(2,4,3)
print(b)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [20]:
#numpy.itemsize
x=np.array([1,2,3,4,5],dtype=np.int32)
print(x)

[1 2 3 4 5]


In [21]:
print(x.itemsize)

4
